### ISSUE TITLE
插件使用异常

### ISSUE THREAD

**Issue by hugodotlau** [Wox-launcher/Wox.Plugin.Youdao#1]
![default](https://cloud.githubusercontent.com/assets/275291/3745425/b1c62a1e-17ab-11e4-9f1e-c0f0fdb953b0.jpg)
有道插件使用时出现这现象，求解。

**Comment by qianlifeng** [comment]
就好像有道API那边有问题，我重新申请的API也是同样的问题。再等等看吧

**Comment by vingi** [comment]
插件的下载页面上所有插件都打不开了...似乎是下载的身份认证异常了..

**Comment by qianlifeng** [comment]
@vingi 具体是指什么？我这边可以打开插件页面

**Comment by vingi** [comment]
@qianlifeng  似乎下载的时候不稳定..而且成功率不高...在昨天晚上的时候.不知道是不是github的问题.
另外在安装多个plugin或者重复安装的过程中..时不时会抛出一些ex...

## Exception

```
Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException: 此单实例应用程序无法连接到原始实例。
   Source: Microsoft.VisualBasic
   TargetAssembly: Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   TargetModule: Microsoft.VisualBasic.DLL
   TargetSite: Void Run(System.String[])
   在 Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   在 Wox.EntryPoint.Main(String[] args) 位置 c:\Projects\Wox\Wox\App.xaml.cs:行号 27

```

## Environment
- Command Line: "E:\mydrive\tools\Wox 1.0.0.219\Wox.exe"
- Exception Handle: System.AppDomain.UnhandledException
- Timestamp: 2014-08-19T22:05:17.5320000+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
- CLR Version: 2.0.50727.5456
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.5420 SP2
  - v3.0 3.0.30729.5420 SP2
  - v3.5 3.5.30729.5420 SP1
  - v4 Client 4.5.50938
  - v4 Full 4.5.50938
  - v4.0 Client 4.0.0.0
  - 4.5.1 installed on Windows 8, Windows 7 SP1, or Windows Vista SP2

## Assemblies - Wox.exe
- Wox, Version=1.0.0.219, Culture=neutral, PublicKeyToken=null (E:\mydrive\tools\Wox 1.0.0.219\Wox.exe)
- mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
- System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
- System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\Microsoft.VisualBasic\8.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
- System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
- Microsoft.VisualBasic.resources, Version=8.0.0.0, Culture=zh-CHS, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\Microsoft.VisualBasic.resources\8.0.0.0_zh-CHS_b03f5f7f11d50a3a\Microsoft.VisualBasic.resources.dll)
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
- mscorlib.resources, Version=2.0.0.0, Culture=zh-CHS, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)

## Modules - Wox
- E:\mydrive\tools\Wox 1.0.0.219\Wox.exe (Wox, 1.0.0.219, Wox, 1.0.0.219, ), 0x00000000013E0000
- C:\Windows\SYSTEM32\ntdll.dll (NT 层 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000076E20000
- C:\Windows\SYSTEM32\MSCOREE.DLL (Microsoft .NET Runtime Execution Engine, 4.0.40305.0 (Main.040305-0000), Microsoft® .NET Framework, 4.0.40305.0, Microsoft Corporation), 0x000007FEF4350000
- C:\Windows\system32\KERNEL32.dll (Windows NT 基本 API 客户端 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000076C00000
- C:\Windows\system32\KERNELBASE.dll (Windows NT 基本 API 客户端 DLL, 6.1.7601.17932 (win7sp1_gdr.120820-0419), Microsoft® Windows® Operating System, 6.1.7601.17932, Microsoft Corporation), 0x000007FEFCF00000
- C:\Windows\system32\ADVAPI32.dll (高级 Windows 32 基本 API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE620000
- C:\Windows\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.7601.17744 (win7sp1_gdr.111215-1535), Microsoft® Windows® Operating System, 7.0.7601.17744, Microsoft Corporation), 0x000007FEFEA70000
- C:\Windows\SYSTEM32\sechost.dll (Host for SCM/SDDL/LSA Lookup APIs, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE750000
- C:\Windows\system32\RPCRT4.dll (远程过程调用运行时, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFF000000
- C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll (Microsoft .NET Runtime Execution Engine, 4.0.30319.18408 built by: FX451RTMGREL, Microsoft® .NET Framework, 4.0.30319.18408, Microsoft Corporation), 0x000007FEF42B0000
- C:\Windows\system32\SHLWAPI.dll (外壳简易实用工具库, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD1E0000
- C:\Windows\system32\GDI32.dll (GDI Client DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFED20000
- C:\Windows\system32\USER32.dll (多用户 Windows 用户 API 客户端 DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x0000000076D20000
- C:\Windows\system32\LPK.dll (Language Pack, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE8F0000
- C:\Windows\system32\USP10.dll (Uniscribe Unicode script processor, 1.0626.7601.17514 (win7sp1_rtm.101119-1850), Microsoft(R) Uniscribe Unicode script processor, 1.0626.7601.17514, Microsoft Corporation), 0x000007FEFE900000
- C:\Windows\system32\IMM32.DLL (Multi-User Windows IMM32 API Client DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFEFD0000
- C:\Windows\system32\MSCTF.dll (MSCTF 服务器 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD260000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.5456 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5456, Microsoft Corporation), 0x000007FEF2CD0000
- C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6229_none_88dcc0bf2fb1b808\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.6229, Microsoft® Visual Studio® 2005, 8.00.50727.6229, Microsoft Corporation), 0x000000006EB40000
- C:\Windows\system32\shell32.dll (Windows 外壳公用 DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFD4F0000
- C:\Windows\system32\ole32.dll (用于 Windows 的 Microsoft OLE, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFEB10000
- C:\Windows\system32\profapi.dll (User Profile Basic API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFCBD0000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\mscorlib\969da204960244f3570058daa0aa3256\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.5456 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5456, Microsoft Corporation), 0x000007FEF1DF0000
- C:\Windows\system32\CRYPTBASE.dll (Base cryptographic API DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFCB00000
- C:\Windows\system32\uxtheme.dll (Microsoft UxTheme 库, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFB340000
- D:\Program Files\Listary\ListaryHook64.dll (Listary Hook, 4.10.1441.0, Listary, 4.10.1441.0, Bopsoft), 0x000007FEEF5D0000
- C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.17514_none_a4d6a923711520a9\COMCTL32.dll (公用控件库, 5.82 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEF9C60000
- C:\Windows\system32\OLEACC.dll (Active Accessibility Core Component, 7.0.0.0 (win7sp1_gdr.110826-1504), Microsoft® Windows® Operating System, 6.1.7601.17676, Microsoft Corporation), 0x000007FEFA7C0000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.5456 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5456, Microsoft Corporation), 0x000007FEF1C60000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System\8d96341906660146e6d2d88cd2ded418\System.ni.dll (.NET Framework, 2.0.50727.5456 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5456, Microsoft Corporation), 0x000007FEF1230000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\ce99b3896089b41320568c19d5c9765f\System.Drawing.ni.dll (.NET Framework, 2.0.50727.5462 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5462, Microsoft Corporation), 0x000007FEF0DB0000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\71a747478a63ef2884e7438c33c17029\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.5460 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5460, Microsoft Corporation), 0x000007FEEA380000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\Microsoft.VisualBas#\77ccfe455be766423320a9dfbcc25846\Microsoft.VisualBasic.ni.dll (Visual Basic Runtime Library, 8.0.50727.5420 (Win7SP1.050727-5400), Microsoft® Visual Studio® 2005, 8.0.50727.5420, Microsoft Corporation), 0x000007FEF1020000
- C:\Windows\system32\dwmapi.dll (Microsoft 桌面窗口管理器 API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFAF60000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Remo#\19e2f8ff362d0bc15838f01472135c01\System.Runtime.Remoting.ni.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.5420 (Win7SP1.050727-5400), Microsoft® .NET Framework, 2.0.50727.5420, Microsoft Corporation), 0x000007FEF0CB0000
- C:\Windows\system32\CRYPTSP.dll (Cryptographic Service Provider API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC4A0000
- C:\Windows\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC1A0000
- C:\Windows\system32\RpcRtRemote.dll (Remote RPC Extension, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFCBB0000
- C:\Windows\system32\ws2_32.dll (Windows Socket 2.0 32 位 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE700000
- C:\Windows\system32\NSI.dll (NSI User-mode interface DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE280000
- C:\Windows\system32\mswsock.dll (Microsoft Windows Sockets 2.0 服务提供程序, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC440000
- C:\Windows\System32\wshtcpip.dll (Winsock2 帮助程序 DLL (TL/IPv4), 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFBDE0000
- C:\Windows\System32\wship6.dll (Winsock2 帮助程序 DLL (TL/IPv6), 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC430000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\8b1ae25f7467dbb0fd5235656c109beb\System.Configuration.ni.dll (System.Configuration.dll, 2.0.50727.5420 (Win7SP1.050727-5400), Microsoft® .NET Framework, 2.0.50727.5420, Microsoft Corporation), 0x000007FEF0B60000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\d498c013bcc2b2f2b7a9ccaf182f0667\System.Xml.ni.dll (.NET Framework, 2.0.50727.5420 (Win7SP1.050727-5400), Microsoft® .NET Framework, 2.0.50727.5420, Microsoft Corporation), 0x000007FEF04B0000
- C:\Windows\assembly\GAC_MSIL\Microsoft.VisualBasic.resources\8.0.0.0_zh-CHS_b03f5f7f11d50a3a\Microsoft.VisualBasic.resources.dll (Visual Basic 运行库, 8.0.50727.4927 (NetFXspW7.050727-4900), Microsoft (R) Visual Studio (R) 2005, 8.0.50727.4927, Microsoft Corporation), 0x0000000073C80000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Core\4adeba53d684048bcf80a47e10f11a73\System.Core.ni.dll (.NET Framework, 3.5.30729.5420 built by: Win7SP1, Microsoft® .NET Framework, 3.5.30729.5420, Microsoft Corporation), 0x000007FEEFE50000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.5420 (Win7SP1.050727-5400), Microsoft® Visual Studio® 2005, 8.0.50727.5420, Microsoft Corporation), 0x0000000516F00000
- C:\Windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_zh-CHS_b77a5c561934e089\mscorlib.resources.dll (Microsoft 公共语言运行时类库, 2.0.50727.5420 (Win7SP1.050727-5400), Microsoft(R) .NET Framework, 2.0.50727.5420, Microsoft Corporation), 0x0000000073810000
- C:\Windows\system32\psapi.dll (Process Status Helper, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000076FF0000

## Threads - 8
- 1620, Running Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000000000000
- 4080, Wait Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520
- 4388, Wait Highest, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520
- 8124, Wait Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520
- 5280, Wait Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520
- 7680, Wait Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520
- 1108, Wait Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520
- 5432, Wait Normal, Started: 2014/8/19 22:05:12, StartAddress: 0x0000000076E4C520

**Comment by qianlifeng** [comment]
@vingi 这个应该是重启Wox的时候报错的吧？后面会修复这个BUG。另外你说的下载不稳定应该是因为墙的原因，新版的下载会将所有的插件放在getwox.com上面，应该不会出现不稳定的情况了。

**Comment by DavidSheh** [comment]
平时工作中挺需要这个插件的，但是有个体验非常不好的地方就是，查出来的单词不能复制，我还得一个个字母敲，不知道作者能不能再加一个复制的功能，可以把查出来的单词复制下来

**Comment by bao-qian** [comment]
@DavidSheh @vingi @hugodotlau 
插件已更新
http://www.getwox.com/plugin/78
