### ISSUE TITLE
对展示结果的建议

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox.Plugin.Youdao#8]
目前的展示结果方式为（复制的都是主标题）
1. 音标，副标题是 解释 （basic.explain）
2. 翻译，无副标题
3. 从第三个开始是网络释义，主标题（居然）是英文，而副标题才是中文释义

我个人比较下图的这种结果展示
![workflow youdao](https://pic1.zhimg.com/1988c69dbc0f1eef8811af9278cff54c_r.jpg)
首先加上了各个解释的含义（简明、网络），不会让人觉得为什么这么多解释还都差不多，其次对于网络释义中英文在主副标题上颠倒了一下，我觉得这才是正确的做法。英翻中不应该把中文放在更重要的地方么？至于复制的内容，我觉得除了第一个翻译结果只需要复制翻译（舍去音标），其他都复制主标题即可。或者把音标单独拆成一项亦可。

**Comment by bao-qian** [comment]
我举双手双脚赞成
你如果能开 pr 就更好了（

**Comment by jhdxr** [comment]
有个问题，怎么更新已安装的插件？

**Comment by bao-qian** [comment]
… 再装一次，我知道略蛋疼…
